apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g465kbr84-python
  janus-idp.io/tekton: g465kbr84-python
  backstage.io/kubernetes-id: g465kbr84-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g465kbr84-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
